addr: :30911
token: eacdn-2020! # if empty auto generate it
providers:
  - type: nginx
    name: nginx
  - type: caddy
    name: caddy
sites:
  - provider: nginx # provider name not type
    host: example.dev
    upstreams:
      - dial: https://www.baidu.com
        weight: 2
      - dial: https://m.baidu.com
        weight: 1
    auto_https:
      disable: false
      disable_redirect: true
    # cache control
